language: ruby
rvm:
  - "2.4.0"
services:
  - postgresql
before_script:
  - psql -c 'create database shiny_rails_test;' -U postgres
  - bin/rails db:migrate
script:
  - bundle exec cucumber
  # - bin/rails db:schema:load
addons:
  sauce_connect: true
env:
  # Linux tests
  - PLATFORM="Linux" BROWSER="firefox"
  - PLATFORM="Linux" BROWSER="chrome"

  # Mac OS X tests
  - PLATFORM="OS X 10.10" BROWSER="firefox"
  - PLATFORM="OS X 10.10" BROWSER="chrome"

  # Windows tests
  - PLATFORM="Windows 7" BROWSER="firefox"
  - PLATFORM="Windows 7" BROWSER="chrome"
  - PLATFORM="Windows 8.1" BROWSER="firefox"
  - PLATFORM="Windows 8.1" BROWSER="chrome"
