version: '2'

volumes:
  db: {}

services:

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 80:3000
      - 443:3000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # db:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db:/var/lib/postgres/data
